/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import logic.Board;
import logic.BoardGenerator;

public class GameWindow extends javax.swing.JFrame
{
    private int n_lin;
    private int n_col;
    private int n_gums;

    public GameWindow()
    {
        this(10, 10, 4);
    }

    public GameWindow(int n_lin, int n_col, int n_gums)
    {
        this.n_lin = n_lin;
        this.n_col = n_col;
        this.n_gums = n_gums;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new BoardPanel(new BoardGenerator(n_lin,n_col,n_gums).nextBoard().getBoard());
        game_menu_bar = new javax.swing.JMenuBar();
        game_menu = new javax.swing.JMenu();
        game_new_game_option = new javax.swing.JMenuItem();
        game_options_option = new javax.swing.JMenuItem();
        game_quit_option = new javax.swing.JMenuItem();
        help_menu = new javax.swing.JMenu();
        help_pacman_101_option = new javax.swing.JMenuItem();
        help_about_option = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 640));
        setMinimumSize(new java.awt.Dimension(1024, 640));
        setPreferredSize(new java.awt.Dimension(1024, 640));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(1024, 640));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 640));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1);

        game_menu.setText("Game");

        game_new_game_option.setText("New");
        game_new_game_option.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                game_new_game_optionActionPerformed(evt);
            }
        });
        game_menu.add(game_new_game_option);

        game_options_option.setText("Options");
        game_menu.add(game_options_option);

        game_quit_option.setText("Quit");
        game_menu.add(game_quit_option);

        game_menu_bar.add(game_menu);

        help_menu.setText("Help");

        help_pacman_101_option.setText("Pacman 101");
        help_pacman_101_option.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                help_pacman_101_optionActionPerformed(evt);
            }
        });
        help_menu.add(help_pacman_101_option);

        help_about_option.setText("About");
        help_about_option.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                help_about_optionMouseClicked(evt);
            }
        });
        help_about_option.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                help_about_optionActionPerformed(evt);
            }
        });
        help_menu.add(help_about_option);

        game_menu_bar.add(help_menu);

        setJMenuBar(game_menu_bar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void help_about_optionMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_help_about_optionMouseClicked
    {//GEN-HEADEREND:event_help_about_optionMouseClicked
    }//GEN-LAST:event_help_about_optionMouseClicked

    private void help_about_optionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_help_about_optionActionPerformed
    {//GEN-HEADEREND:event_help_about_optionActionPerformed
    }//GEN-LAST:event_help_about_optionActionPerformed

    private void help_pacman_101_optionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_help_pacman_101_optionActionPerformed
    {//GEN-HEADEREND:event_help_pacman_101_optionActionPerformed
        OpenBrowser.openURL("http://en.wikipedia.org/wiki/Pac-Man");
    }//GEN-LAST:event_help_pacman_101_optionActionPerformed

    private void game_new_game_optionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_game_new_game_optionActionPerformed
    {//GEN-HEADEREND:event_game_new_game_optionActionPerformed
        
    }//GEN-LAST:event_game_new_game_optionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        BoardGenerator b_gen = new BoardGenerator(30, 30, 4);
        final Board board = b_gen.nextBoard();

        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                new GameWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu game_menu;
    private javax.swing.JMenuBar game_menu_bar;
    private javax.swing.JMenuItem game_new_game_option;
    private javax.swing.JMenuItem game_options_option;
    private javax.swing.JMenuItem game_quit_option;
    private javax.swing.JMenuItem help_about_option;
    private javax.swing.JMenu help_menu;
    private javax.swing.JMenuItem help_pacman_101_option;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
