package gui;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.UIManager;

public class StartWindow extends javax.swing.JFrame implements ActionListener, MouseListener
{
    /**
     * Creates new form StartWindow
     */
    public StartWindow()
    {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        start_container = new javax.swing.JPanel();
        max_points_button = new javax.swing.JButton();
        new_game_button = new javax.swing.JButton();
        options_button = new javax.swing.JButton();
        exit_button = new javax.swing.JButton();
        about_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusTraversalPolicyProvider(true);
        setForeground(java.awt.Color.white);
        setMaximumSize(new java.awt.Dimension(1024, 640));
        setMinimumSize(new java.awt.Dimension(1024, 640));
        setPreferredSize(new java.awt.Dimension(1024, 640));
        setResizable(false);
        getContentPane().setLayout(null);

        start_container.setMaximumSize(new java.awt.Dimension(1024, 640));
        start_container.setMinimumSize(new java.awt.Dimension(1024, 640));
        start_container.setOpaque(false);
        start_container.setPreferredSize(new java.awt.Dimension(1024, 640));
        start_container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        max_points_button.setText("High Scores");
        max_points_button.setOpaque(false);
        max_points_button.addActionListener(this);
        start_container.add(max_points_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 580, 120, -1));

        new_game_button.setBackground(new java.awt.Color(0, 0, 0));
        new_game_button.setText("New Game");
        new_game_button.setOpaque(false);
        new_game_button.addMouseListener(this);
        new_game_button.addActionListener(this);
        start_container.add(new_game_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 120, -1));

        options_button.setText("Options");
        options_button.setOpaque(false);
        options_button.addMouseListener(this);
        options_button.addActionListener(this);
        start_container.add(options_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 580, 120, -1));

        exit_button.setText("Exit");
        exit_button.setOpaque(false);
        exit_button.addMouseListener(this);
        exit_button.addActionListener(this);
        start_container.add(exit_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 580, 120, -1));

        about_button.setText("About");
        about_button.setOpaque(false);
        about_button.addMouseListener(this);
        about_button.addActionListener(this);
        start_container.add(about_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 580, 120, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cristiano Rodrigues\\NetBeansProjects\\Pacman-LPOO2\\textures\\main_window_title.png")); // NOI18N
        jLabel1.setText("jLabel1");
        start_container.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 490, 130));

        getContentPane().add(start_container);
        start_container.setBounds(0, 0, 1024, 640);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cristiano Rodrigues\\NetBeansProjects\\Pacman-LPOO2\\textures\\background_start_window.jpg")); // NOI18N
        jLabel2.setLabelFor(jLabel2);
        jLabel2.setDoubleBuffered(true);
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1024, 640);

        pack();
    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(java.awt.event.ActionEvent evt) {
        if (evt.getSource() == max_points_button) {
            StartWindow.this.max_points_buttonActionPerformed(evt);
        }
        else if (evt.getSource() == new_game_button) {
            StartWindow.this.new_game_buttonActionPerformed(evt);
        }
        else if (evt.getSource() == options_button) {
            StartWindow.this.options_buttonActionPerformed(evt);
        }
        else if (evt.getSource() == exit_button) {
            StartWindow.this.exit_buttonActionPerformed(evt);
        }
        else if (evt.getSource() == about_button) {
            StartWindow.this.about_buttonActionPerformed(evt);
        }
    }

    public void mouseClicked(java.awt.event.MouseEvent evt) {
        if (evt.getSource() == new_game_button) {
            StartWindow.this.new_game_buttonMouseClicked(evt);
        }
        else if (evt.getSource() == options_button) {
            StartWindow.this.options_buttonMouseClicked(evt);
        }
        else if (evt.getSource() == exit_button) {
            StartWindow.this.exit_buttonMouseClicked(evt);
        }
        else if (evt.getSource() == about_button) {
            StartWindow.this.about_buttonMouseClicked(evt);
        }
    }

    public void mouseEntered(java.awt.event.MouseEvent evt) {
    }

    public void mouseExited(java.awt.event.MouseEvent evt) {
    }

    public void mousePressed(java.awt.event.MouseEvent evt) {
    }

    public void mouseReleased(java.awt.event.MouseEvent evt) {
    }// </editor-fold>//GEN-END:initComponents

    private void exit_buttonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_exit_buttonActionPerformed
    {//GEN-HEADEREND:event_exit_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exit_buttonActionPerformed

    private void exit_buttonMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_exit_buttonMouseClicked
    {//GEN-HEADEREND:event_exit_buttonMouseClicked
        if (new ConfirmExitDialog().ask())
        {
            System.exit(0);
        }
    }//GEN-LAST:event_exit_buttonMouseClicked

    private void options_buttonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_options_buttonActionPerformed
    {//GEN-HEADEREND:event_options_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_options_buttonActionPerformed

    private void max_points_buttonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_max_points_buttonActionPerformed
    {//GEN-HEADEREND:event_max_points_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_max_points_buttonActionPerformed

    private void new_game_buttonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_new_game_buttonActionPerformed
    {//GEN-HEADEREND:event_new_game_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_new_game_buttonActionPerformed

    private void about_buttonMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_about_buttonMouseClicked
    {//GEN-HEADEREND:event_about_buttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_about_buttonMouseClicked

    private void about_buttonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_about_buttonActionPerformed
    {//GEN-HEADEREND:event_about_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_about_buttonActionPerformed

    private void options_buttonMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_options_buttonMouseClicked
    {//GEN-HEADEREND:event_options_buttonMouseClicked
        new OptionsDialog(this, true).setVisible(true);
    }//GEN-LAST:event_options_buttonMouseClicked

    private void new_game_buttonMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_new_game_buttonMouseClicked
    {//GEN-HEADEREND:event_new_game_buttonMouseClicked
        GameWindow gw = new GameWindow(19,33,10);
        gw.setLocationRelativeTo(this);
        this.setVisible(false);
        gw.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_new_game_buttonMouseClicked

    public static void main(String args[])
    {
        try
        {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        }
        catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(StartWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                new StartWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton about_button;
    javax.swing.JButton exit_button;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel2;
    javax.swing.JButton max_points_button;
    javax.swing.JButton new_game_button;
    javax.swing.JButton options_button;
    javax.swing.JPanel start_container;
    // End of variables declaration//GEN-END:variables
}
