package gui;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

public class StartWindow extends javax.swing.JFrame implements ActionListener, MouseListener
{
    Image background = Toolkit.getDefaultToolkit().createImage("\\Textures\\background_start_window.jpg");

    /**
     * Creates new form StartWindow
     */
    public StartWindow()
    {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new ImagePanel(background);
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        MaxPointsButton = new javax.swing.JButton();
        NewGameButton = new javax.swing.JButton();
        OptionsButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.white);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel7.setMaximumSize(new java.awt.Dimension(1360, 700));
        jPanel7.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel7.setOpaque(false);
        jPanel7.setLayout(new java.awt.GridLayout(1, 5));

        jPanel4.setMaximumSize(new java.awt.Dimension(1360, 700));
        jPanel4.setOpaque(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 337, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel4);

        jPanel6.setMaximumSize(new java.awt.Dimension(1360, 700));
        jPanel6.setOpaque(false);
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MaxPointsButton.setText("Pontuações Máx.");
        MaxPointsButton.addActionListener(this);
        jPanel6.add(MaxPointsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 120, -1));

        NewGameButton.setText("Novo jogo");
        jPanel6.add(NewGameButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 120, -1));

        OptionsButton.setText("Opções");
        OptionsButton.addActionListener(this);
        jPanel6.add(OptionsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 120, -1));

        ExitButton.setText("Sair");
        ExitButton.addMouseListener(this);
        ExitButton.addActionListener(this);
        jPanel6.add(ExitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 540, 120, -1));

        jPanel7.add(jPanel6);

        jPanel8.setMaximumSize(new java.awt.Dimension(1360, 700));
        jPanel8.setOpaque(false);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 337, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel8);

        getContentPane().add(jPanel7);

        pack();
    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(java.awt.event.ActionEvent evt) {
        if (evt.getSource() == MaxPointsButton) {
            StartWindow.this.MaxPointsButtonActionPerformed(evt);
        }
        else if (evt.getSource() == OptionsButton) {
            StartWindow.this.OptionsButtonActionPerformed(evt);
        }
        else if (evt.getSource() == ExitButton) {
            StartWindow.this.ExitButtonActionPerformed(evt);
        }
    }

    public void mouseClicked(java.awt.event.MouseEvent evt) {
        if (evt.getSource() == ExitButton) {
            StartWindow.this.ExitButtonMouseClicked(evt);
        }
    }

    public void mouseEntered(java.awt.event.MouseEvent evt) {
    }

    public void mouseExited(java.awt.event.MouseEvent evt) {
    }

    public void mousePressed(java.awt.event.MouseEvent evt) {
    }

    public void mouseReleased(java.awt.event.MouseEvent evt) {
    }// </editor-fold>//GEN-END:initComponents

    private void OptionsButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_OptionsButtonActionPerformed
    {//GEN-HEADEREND:event_OptionsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OptionsButtonActionPerformed

    private void MaxPointsButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_MaxPointsButtonActionPerformed
    {//GEN-HEADEREND:event_MaxPointsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaxPointsButtonActionPerformed

    private void ExitButtonMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_ExitButtonMouseClicked
    {//GEN-HEADEREND:event_ExitButtonMouseClicked
        if (new ConfirmExitDialog().ask())
            System.exit(0);
    }//GEN-LAST:event_ExitButtonMouseClicked

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ExitButtonActionPerformed
    {//GEN-HEADEREND:event_ExitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        try
        {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        }
        catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(StartWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                new StartWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton ExitButton;
    javax.swing.JButton MaxPointsButton;
    javax.swing.JButton NewGameButton;
    javax.swing.JButton OptionsButton;
    javax.swing.JPanel jPanel4;
    javax.swing.JPanel jPanel6;
    javax.swing.JPanel jPanel7;
    javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}
